consumers:
  - username: nokamoto
    custom_id: nokamoto
    present: yes
    key_auths:
      - key: my-api-key
        present: yes

services:
  - name: mock
    url: http://mockbin.org
    present: yes
    routes:
      - hosts:
          - example.com
        protocols:
          - http