version: "3"

services:
  kong-database:
    image: "cassandra:3"
    restart: always

  kong-migration:
    image: "kong:0.13"
    command: "kong migrations up"
    restart: on-failure
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    depends_on:
      - kong-database

  kong:
    image: "kong:0.13"
    restart: always
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000"
      - "8001:8001"

  golang:
    image: "golang:1.10.3"
    working_dir: "/go/src/github.com/nokamoto/kfig"
    volumes:
      - ".:/go/src/github.com/nokamoto/kfig"